### ISSUE TITLE
Throw exception when columns are not found

### ISSUE THREAD

**Issue by mielvds** [AtomGraph/CSV2RDF#4]
When you refer to an unexisting column, the tool fails silently and no output is produced. It takes a while until you notice this is the problem.

Would it be an idea to throw a suitable exception for this and add a flag to surpress these errors if desired?

**Comment by namedgraph** [comment]
Hi. Thanks for feedback.

What constitutes the "missing" column? A column specified in the `WHERE` clause but not present in CSV?

In that case I'm not sure anything can be done in this processing model - the intermediate CSV/RDF representation will be naturally missing properties for the columns that were missing, and so the `WHERE` pattern will not match anything. There's no checking done, just plain SPARQL execution.

Does that make sense? If not, or if you mean something else, please provide an example.

**Comment by mielvds** [comment]
It does! I guess I just had to wrap my head around the concept that you're doing a direct mapping first. I like this approach though. A warning that your WHERE does not match anything would be nice, but probably hard to do.
