### ISSUE TITLE
How to convert CSV into RDF with both value and unit information?

### ISSUE THREAD

**Issue by chunhualiao** [AtomGraph/CSV2RDF#6]
Does CSV2RDF support using unit ontologies?

CSV data often have units associated,  such as kilograms, grams, or microsecond, nanosecond, second etc.

One example is something has a weight of 2.4 kilograms:

exproduct:item10245 exterms:weight [ rdf:value "2.4"^^xsd:decimal ; exterms:units exunits:kilograms ] .

**Comment by namedgraph** [comment]
Hi. Can you give an example of the CSV? Assuming the structure is something like
```
id,value,unit
item10245,2.4,kg
```

then in the SPARQL query you can do smth like that using [`VALUES`](https://www.w3.org/TR/sparql11-query/#inline-data):
```sparql
PREFIX exproduct: <http://exproduct>
PREFIX exterms: <http://exterms>
PREFIX exunits: <http://exunits>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

CONSTRUCT
{
    ?item exterms:weight [
        rdf:value ?value ;
        exterms:units ?unit
    ] .
}
{
    ?itemRow <#id>  ?id ;
        <#value> ?valueStr ;
        <#unit> ?unitStr .

    BIND(URI(CONCAT(STR(exproduct:), ?id)) AS ?item)
    BIND (xsd:decimal(?valueStr) AS ?value)
    VALUES (?unitStr ?unit) {
        ("kg" exunits:kilograms)
        ("g" exunits:grams)
    }
}
```
Not tested, but "should work" :) If it doesn't, I can take a second look. But I hope it gives you the idea.

If I understand the use case, it is not specific to unit ontologies, more a matter of providing an additional data table into the process (which is what `VALUES` does).

**Comment by chunhualiao** [comment]
Your syntax of 
CONSTRUCT
{
    ?item exterms:weight [
        rdf:value ?value ;
        exterms:units ?unit
    ] .
}
works for me!   Thanks a lot.
